xtermjs/xtermjs.org

_docs/api/Terminal.md, css/main.scss
Initial issue: sourcelair/xterm.js#313
=> Document constructor

_docs/api/Terminal.md
Closes sourcelair/xterm.js#315.
=> Document title event

_docs/api/Terminal.md, _docs/api/addons/attach.md, _docs/api/addons/fit.md, _docs/api/addons/fullscreen.md, _docs/api/addons/terminado.md, _docs/guides/terminado.md, _docs/guides/using-addons.md, _layouts/docs.html, _pages/docs.html
Closes sourcelair/xterm.js#306.
=> Document addons

_config.yml
This should be merged, after we release xterm.js 2.4.0.
=> Bump to 2.4.0

_docs/api/Terminal.md
=> Document attachCustomKeyEventHandler

_docs/api/Terminal.md
Fix https://github.com/xtermjs/xtermjs.org/issues/28
=> Update docs for lineFeed event

_docs/api/Terminal.md
Related sourcelair/xterm.js#1089
=> Clarify that the parent needs to be visible

_docs/api/Terminal.md
=> Fix grammar.

_docs/guides/terminado.md
=> Update terminado guide with new add-on API

_includes/getting-started.md, _includes/xtermjs-description.md, _pages/index.html
=> Synchronize site with xterm.js README.md 

_includes/footer.html
=> Update authors in footer

_docs/api/terminal/classes/terminal.md, _docs/api/terminal/interfaces/idisposable.md, _docs/api/terminal/interfaces/ieventemitter.md, _docs/api/terminal/interfaces/ilinkmatcheroptions.md, _docs/api/terminal/interfaces/ilocalizablestrings.md, _docs/api/terminal/interfaces/imarker.md, _docs/api/terminal/interfaces/iterminaloptions.md, _docs/api/terminal/interfaces/itheme.md, _docs/api/terminal/modules/xterm.md, gulpfile.js
=> Pin API links to the latest version branch

_config.yml, gulpfile.js
=> Fix API version number

_includes/getting-started.md, _includes/xtermjs-description.md
Sync changes with xtermjs/xterm.js#1856
=> Sync getting started and description

_includes/real-world-uses.md
Signed-off-by: Jianhui Zhao <jianhuizhao329@gmail.com>
=> Modify Real-world uses.

js/demo.js
=> Fix backspace in demo

_docs/guides/import.md
=> Broken Link

_includes/getting-started.md, js/demo.js
=> More fixes for v4

_docs/guides/flowcontrol.md
=> flow control stub

_docs/guides/encoding.md
- onBinary description
- rephrase some legacy encoding parts
=> update encoding article

README.md, _config.yml, _docs/api/terminal/classes/terminal.md, _docs/api/terminal/interfaces/ibuffer.md, _docs/api/terminal/interfaces/ibuffercell.md, _docs/api/terminal/interfaces/ibufferline.md, _docs/api/terminal/interfaces/idisposable.md, _docs/api/terminal/interfaces/ievent.md, _docs/api/terminal/interfaces/ifunctionidentifier.md, _docs/api/terminal/interfaces/ilinkmatcheroptions.md, _docs/api/terminal/interfaces/ilocalizablestrings.md, _docs/api/terminal/interfaces/imarker.md, _docs/api/terminal/interfaces/iparser.md, _docs/api/terminal/interfaces/iselectionposition.md, _docs/api/terminal/interfaces/iterminaladdon.md, _docs/api/terminal/interfaces/iterminaloptions.md, _docs/api/terminal/interfaces/itheme.md, _docs/api/terminal/interfaces/iunicodehandling.md, _docs/api/terminal/interfaces/iunicodeversionprovider.md, _docs/api/terminal/interfaces/iviewportrange.md, _docs/api/terminal/interfaces/iviewportrangeposition.md, _docs/api/terminal/interfaces/iwindowoptions.md, _docs/api/terminal/modules/xterm.md
Something appears to be broken, descriptions have disappeared ☹️
=> Update docs for v4.4

js/demo.js
=> Use ^ over angled arrow

_config.yml, _docs/api/terminal/classes/terminal.md, _docs/api/terminal/interfaces/ibuffer.md, _docs/api/terminal/interfaces/ibuffercell.md, _docs/api/terminal/interfaces/ibuffercellposition.md, _docs/api/terminal/interfaces/ibufferline.md, _docs/api/terminal/interfaces/ibuffernamespace.md, _docs/api/terminal/interfaces/ibufferrange.md, _docs/api/terminal/interfaces/idisposable.md, _docs/api/terminal/interfaces/ievent.md, _docs/api/terminal/interfaces/ifunctionidentifier.md, _docs/api/terminal/interfaces/ilink.md, _docs/api/terminal/interfaces/ilinkdecorations.md, _docs/api/terminal/interfaces/ilinkmatcheroptions.md, _docs/api/terminal/interfaces/ilinkprovider.md, _docs/api/terminal/interfaces/ilocalizablestrings.md, _docs/api/terminal/interfaces/imarker.md, _docs/api/terminal/interfaces/imodes.md, _docs/api/terminal/interfaces/iparser.md, _docs/api/terminal/interfaces/iselectionposition.md, _docs/api/terminal/interfaces/iterminaladdon.md, _docs/api/terminal/interfaces/iterminaloptions.md, _docs/api/terminal/interfaces/itheme.md, _docs/api/terminal/interfaces/iunicodehandling.md, _docs/api/terminal/interfaces/iunicodeversionprovider.md, _docs/api/terminal/interfaces/iviewportrange.md, _docs/api/terminal/interfaces/iviewportrangeposition.md, _docs/api/terminal/interfaces/iwindowoptions.md, _docs/api/terminal/modules/xterm.md, _docs/api/vtfeatures.md
=> Update website for 4.14

_posts/2017-03-08-xtermjs-2.4.md
This is a really cool project, I just saw this while browsing the website. :)
=> Fix spelling error "tje"

.vscode/tasks.json, package.json
=> Fix default vscode build task

js/demo.js
=> Add chars command to demo

_includes/getting-started.md, gulpfile.js
=> Update script/css imports for scoped packages

_includes/getting-started.md, _pages/index.html
This updates the `npm` examples to have the @xterm package scope.
=> Add @xterm package scope

_docs/guides/link-handling.md
I've implemented these in my DomTerm embedding of xterm.js. They might be helpful for others. And of course feedback is welcome.
=> documentation: Some suggestions for link handling.
